### ISSUE TITLE
Use React Fragment

### ISSUE THREAD

**Issue by awaisabir** [ShaneMatthias/Portfolio#1]
https://github.com/ShaneMatthias/Portfolio/blob/c7bb1b3bfd3c7978bc1c61afc1fa10d44bf3a7f5/src/components/App.js#L11

Instead of appending arbitrary `div`'s to the DOM, you can make use of React Fragments like this:

```
import React, { Component, Fragment } from 'react';
import Navbar from './Navbar';
import About from './About';
import Banner from './Banner'; 
import Employment from './Employment';
import '../styles/App.css';

class App extends Component {
  render() {
    return (
      <Fragment>
        <Navbar />
        <Banner />
        <About />
        <Employment />
      </Fragment>
    );
  }
}

export default App;
```

or better yet you can replace `<Fragment>` with `<>` like this:
```
     <>
        <Navbar />
        <Banner />
        <About />
        <Employment />
     </>
```

Cheers 🍻

**Comment by srowhani** [comment]
What's wrong with divs?

**Comment by awaisabir** [comment]
Listen here @srowhani  ... I don't want random additions to the DOM.

**Comment by srowhani** [comment]
Why did you close this, it hasn't been resolved?
